adding debug

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -53,7 +53,7 @@ jobs:
         run: |
           echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
           echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
-          aws sts get-caller-identity || exit 1 # Exit with code 1 if this fails
+          aws sts get-caller-identity --debug|| exit 1 # Exit with code 1 if this fails
 
       - name: Configure AWS CLI
         env:
