fix aws provideer

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -44,14 +44,24 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
+      - name: Validate AWS Credentials
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }} # Optional
+        run: |
+          echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
+          echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
+          aws sts get-caller-identity || exit 1 # Exit with code 1 if this fails
+
       - name: Configure AWS CLI
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }} # Optional
         run: |
-          aws sts get-caller-identity
-          aws configure set region us-east-2 # Set your desired region here
+          aws configure set region us-east-2
+          aws sts get-caller-identity || exit 1 
 
       - name: Set up Terraform
         uses: hashicorp/setup-terraform@v2
